#include "debug/dwarf.h"

namespace toycc::debug {
    std::unordered_map<Form, Class> TO_CLASS = {
        {Form::DW_FORM_addr,           Class::address},
        {Form::DW_FORM_block2,         Class::block},
        {Form::DW_FORM_block4,         Class::block},
        {Form::DW_FORM_data2,          Class::constant},
        {Form::DW_FORM_data4,          Class::constant},
        {Form::DW_FORM_data8,          Class::constant},
        {Form::DW_FORM_string,         Class::string},
        {Form::DW_FORM_block,          Class::block},
        {Form::DW_FORM_block1,         Class::block},
        {Form::DW_FORM_data1,          Class::constant},
        {Form::DW_FORM_flag,           Class::flag},
        {Form::DW_FORM_sdata,          Class::constant},
        {Form::DW_FORM_strp,           Class::string},
        {Form::DW_FORM_udata,          Class::constant},
        {Form::DW_FORM_ref_addr,       Class::reference},
        {Form::DW_FORM_ref1,           Class::reference},
        {Form::DW_FORM_ref2,           Class::reference},
        {Form::DW_FORM_ref4,           Class::reference},
        {Form::DW_FORM_ref8,           Class::reference},
        {Form::DW_FORM_ref_udata,      Class::reference},
        {Form::DW_FORM_indirect,       Class::indirect},
        {Form::DW_FORM_sec_offset,     Class::pointer},
        {Form::DW_FORM_exprloc,        Class::exprloc},
        {Form::DW_FORM_flag_present,   Class::flag},
        {Form::DW_FORM_strx,           Class::string},
        {Form::DW_FORM_addrx,          Class::address},
        {Form::DW_FORM_ref_sup4,       Class::reference},
        {Form::DW_FORM_strp_sup,       Class::string},
        {Form::DW_FORM_data16,         Class::constant},
        {Form::DW_FORM_line_strp,      Class::string},
        {Form::DW_FORM_ref_sig8,       Class::reference},
        {Form::DW_FORM_implicit_const, Class::constant},
        {Form::DW_FORM_loclistx,       Class::loclist},
        {Form::DW_FORM_rnglistx,       Class::rnglist},
        {Form::DW_FORM_ref_sup8,       Class::reference},
        {Form::DW_FORM_strx1,          Class::string},
        {Form::DW_FORM_strx2,          Class::string},
        {Form::DW_FORM_strx3,          Class::string},
        {Form::DW_FORM_strx4,          Class::string},
        {Form::DW_FORM_addrx1,         Class::address},
        {Form::DW_FORM_addrx2,         Class::address},
        {Form::DW_FORM_addrx3,         Class::address},
        {Form::DW_FORM_addrx4,         Class::address},
    };
}
