#include "config.h"
#include "diagnostic.h"
#include "ir/declaration.h"
#include "ir/type.h"
#include "arch/x86_64/execmodel.h"
#include "arch/x86_64/allocation.h"
#include "util/strings.h"
#include "util/alignment.hpp"

namespace toycc::arch::x86_64 {
    // -------- StackFrame
    static const std::unordered_set<Location> NONUNIQUE_LOCATIONS = {Location::constant, Location::memory, Location::stack};

    StackFrame::StackFrame(const ir::Procedure& procedure) : ir::StackFrame<Location>(procedure, NONUNIQUE_LOCATIONS), name(procedure.declaration->name) {
        auto& declaration_index = allocations.get<ir::declaration_tag>();

        size_t integer_parameter_index = 0;
        for (std::shared_ptr<ir::Declaration> parameter : procedure.parameters) {
            if (parameter->type->category == ir::TypeCategory::INTEGER)
                declaration_index.insert(Allocation {parameter, INTEGER_REGISTER_ARGUMENTS[integer_parameter_index++]});
            else throw Diagnostic(DiagnosticLevel::NOT_IMPLEMENTED, "Non-integer function parameters are not implemented", parameter->location);
        }
    }

    std::unordered_set<Location> StackFrame::locate(const ir::Operand& operand) const {
        if (operand.is_dereference())
            return {Location::memory};
        else if (operand.is_constant())
            return {Location::constant};
        else if (operand.is_label())
            return {Location::constant};
        else if (operand.is_variable())
            return ir::StackFrame<Location>::locate(operand.declaration());
        throw Diagnostic(DiagnosticLevel::INTERNAL_ERROR, "Unknown operand type", operand.location);
    }

    // If one is available, return a free location among the `locations`
    std::optional<Location> StackFrame::allocate(const std::unordered_set<Location>& locations) const {
        const auto& location_index = allocations.template get<ir::location_tag>();
        for (Location location : locations) {
            if (location == Location::constant || location == Location::memory || location == Location::stack)
                continue;  // FIXME : For now, don't allocate additional space on the stack for intermediate allocations

            if (location_index.find(location) == location_index.end())
                return location;
        }
        return {};
    }

     bool StackFrame::is_free(Location location) const {
         if (location == Location::constant || location == Location::memory || location == Location::stack)
             return true;
         else
             return content(location).get() == nullptr;
    }

    // Create an intermediate declaration valid only within a code generation iteration. The variable is not inserted into the stack frame unless `offset` is called on it.
    std::shared_ptr<ir::Declaration> StackFrame::declare_intermediate(std::shared_ptr<ir::Type> type, CodeLocation code_location) {
        const std::string variable_name = std::format(".{}.SI{}", name, unique_id++);
        std::shared_ptr<ir::Declaration> declaration = std::make_shared<ir::Declaration>
                (variable_name, type, code_location,ir::StorageClass::AUTO | ir::StorageClass::TEMPORARY | ir::StorageClass::INTERMEDIATE);
        intermediates.insert(declaration);
        return declaration;
    }

    // Destroy all intermediates generated by `declare_intermediate`
    void StackFrame::flush_intermediates() {
        auto& declaration_index = allocations.get<ir::declaration_tag>();
        for (std::shared_ptr<ir::Declaration> intermediate : intermediates)
            declaration_index.erase(intermediate);
        intermediates.clear();
    }

    std::string StackFrame::str() const {
        CodeOutput code;

        code.statement("pushq %rbp");
        code.statement("movq %rsp, %rbp");
        if (current_offset > 0)
            code.statement(std::format("subq ${}, %rsp", align_offset(current_offset, 16)));  // The stack pointer must be aligned to 16 bytes before making a call

        code << output;
        return code.str();
    }

    std::string StackFrame::dump() const {
        std::stringstream result;
        result << "Frame " << name << " {code = {\n";
        result << indent(output.str(), true, "    ");
        result << "    }, allocations = {";
        result << dump_allocations();
        result << "}}";
        return result.str();
    }

    void StackFrame::label(std::string name) {
        output.label(name);
    }

    void StackFrame::statement(std::string code) {
        if (toycc::config::with_comment_trace)
            code = std::format("{}  # {}", code, dump_allocations());
        output.statement(code);
    }

    void StackFrame::directive(std::string code) {
        output.directive(code);
    }

    void StackFrame::comment(std::string code) {
        output.comment(code);
    }

    std::string StackFrame::dump_allocations() const {
        std::stringstream result;
        for (const Allocation& allocation : allocations)
            result << allocation.declaration->name << ": " << allocation.location << ", ";
        return result.str();
    }


    CodeOutput& operator<< (CodeOutput& output, const StackFrame& code) {
        output << code.str();
        return output;
    }
}
